title: Swati Gajjar
tagline: QA Engineer | Automation Tester | SDET-in-Progress
description: My personal portfolio, blog, and projects.
url: "https://swatibhavsar.github.io/"

author:
  name: Swati Gajjar
  bio: >-
    Passionate QA Engineer with automation experience. Exploring AI and Blockchain testing.
  email: swatibhavsar93@gmail.com
  links:
    - label: GitHub
      url: https://github.com/swatisbhavsar
    - label: LinkedIn
      url: https://www.linkedin.com/in/swati-gajjar-209b45141/
